### ISSUE TITLE
[1.12.x] Items show up in all creative tabs.

### ISSUE THREAD

**Issue by BrisingrAerowing** [ben-mkiv/OCGlasses#2]
As per title. You need to call the isInCreativeTab method in the getSubItems method of the glasses item. Other mods had this issue as well.

[Here is a commit in MrCrayfish's Furniture mod that fixed the issue there](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/5bfed48c55ebad82f27ed3fbbbe0bf74bf7dc69c)

Also, there is one new commit in the repository you forked from that adds a new event. You may want to look at that and add it here (if you don't already have something like it).

**Comment by ben-mkiv** [comment]
Hi, thanks much for bringing that up to my attention, going to fix it for the next release.

The event which wasn't merged on git was merged manual before, so the screen size stuff is already in :)

**Comment by BrisingrAerowing** [comment]
Ah, OK. Thanks!
