### ISSUE TITLE
Crash with newer OC Dev Versions

### ISSUE THREAD

**Issue by BrisingrAerowing** [ben-mkiv/OCGlasses#3]
OC changed the wireless card to have two tiers (the old one is tier 2 and there is a new and rather limited tier 1 card), which caused the names to change. For what you are currently using, [this line](https://github.com/ben-mkiv/OCGlasses/blob/MC1.12.1/src/main/java/com/bymarcin/openglasses/OpenGlasses.java#L180) needs to be changed to read as follows:

```java
ItemStack wlanCard = Items.get("wlancard2").createItemStack(1);
```

**Comment by payonel** [comment]
i tried to set up aliases, apparently i goofed. I'll test this and fix our dev builds if needed

**Comment by ben-mkiv** [comment]
closing this, issue is resolved within opencomputer :+1:
